services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb
    restart: always
    expose:
      - 3306
    volumes:
     - mariadb_data:/var/lib/mysql
    user: mysql:mysql
    networks:
      - DockerNet
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress/.
    image: wordpress
    restart: always
    expose:
      - 9000
    volumes:
      - wordpress_html_data:/var/www/html
    networks:
      - DockerNet
    env_file:
      - .env
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx/.
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_html_data:/var/www/html
    networks:
      - DockerNet
    env_file:
      - .env
volumes:
  wordpress_html_data:
    driver: local
    driver_opts:
      type: volume
      device: /home/jde-orma/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: volume
      device: /home/jde-orma/data/mariadb
      o: bind
networks:
  DockerNet:
    driver: bridge
